---
title: "Incarceration Trends Report"
author: "Jennifer Oh"
date: '2022-11-21'
output: html_document
---

```

## Abstract 
[The Vera institute of Justice had created an Incarceration Trends Dataset. The Vera Institute of Justice works to create and build justice systems that promote equity, safety and to strengthen communities. This data set utilized to inform the public dialogue, advance research and create change to justice policies and practices on mass incarceration.]
 

```
As you know, this is a markdown report. The [R Markdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) is **useful!**

* Here's a test of a dynamic variable. Say **"`r q1_string`!!!** 
* Here's another test. A vector
of numbers: `r test_query2(num)`.

Recall that _{r echo=TRUE}_ can be used to display the code, 
which is very useful when developing and debugging a report. Here's an example: 

```{r echo=TRUE}
num <- 5
sum <- sum(test_query2(num))
print(sum)
```

## Introduction 
To give insight on the project history, Vera had released the Incarceration Trends data tool in December 2015. and had partnered with two Bureau of Justice Statistics data collections: which include the Census of Jails and the Annual Survey of Jails. Within 2016-2017, Vera had gained a grant from the MacArthur Foundation Safety and Justice Challenge to update the data tool to include newly released data from 2013- 2015 had had developed four publications which include 'overlooked: Women and Jails in an Era of Reform', 'Out of Sight: The Growth of Jails in Rural America', 'Divided Justice: Trends in Black and White Incarceration 1990-2013', and 'The New Dynamics of Mass Incarceration.' Vera had initially created a county-level data set, however with gaining a grant from Google, they were able to merge this data with the original jails dataset to produce the first national dataset that examines jail and prison incarceration at the county level. When considering the direct and indirect stakeholders that are impacted by research into this data set, the dataset viewer must consider the fact that research on incarceration is traditionally centered on state-level data meaning that state prison populations or the statewide combined prison and jail population. Utilizing the state as a basis for analysis is sufficient when looking at these numbers in a broad context, however this does not provide detailed information to analyze the causes and consequences of these incarcerations. With county-level data, this creates a foundation for more theoretically grounded studies to be made about the high rates of incarceration prominent in the United States. 

## Data Summary 
library("dplyr")
library("tidyr")
library("ggplot2")
incarceration <- read.csv("https://raw.githubusercontent.com/vera-institute/incarceration-trends/master/incarceration_trends.csv" stringsAsFactors = TRUE)
summary(incarceration)
summary(incarceration$total_jail_pop)
summary(incarceration$black_jail_pop)
summary(incarceration$latinx_jail_pop)
summary(incarceration$native_jail_pop)
summary(incarceration$white_jail_pop)

mean(incarceration$total_jail_pop)
mean(incarceration$total_jail_pop, na.rm =TRUE)

mean(incarceration$black_jail_pop)
mean(incarceration$black_jail_pop, na.rm = TRUE)

mean(incarceration$latinx_jail_pop)
mean(incarceration$latinx_jail_pop, na.rm = TRUE)

mean(incarceration$native_jail_pop)
mean(incarceration$native_jail_pop, na.rm = TRUE)

mean(incarceration$white_jail_pop)
mean(incarceration$white_jail_pop, na.rm = TRUE)


Data Summary information: With the values that were calculated with the codes above it shows that the total mean of jail population = 161.12, mean of black jail population= 81.18, mean of latinx jail population = 33.13, mean of native jail population = 2.48, and the mean of white jail population = 90.66. With the means of the total jail population compared to the means of jail populations of different races, It was prominent that there is indeed a pattern of race inequality within the prison system, showing that the there is a huge difference of the means of jail population for different races.


[TODO ... other sections ... See Canvas for details]



_All the very best with your work!_

